services:
  - type: web
    name: resume-analyzer-backend
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn career_ai_backend.wsgi:application"
    plan: free
    healthCheckPath: /api/health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: resume-analyzer-db
          property: connectionString
      - key: GEMINI_API_KEY
        value: AIzaSyAb4pCUvMuCyiL_Y3clHlBa6DG6o_axUwg
      - key: EMAIL_HOST_USER
        value: your_email@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: your_app_password
      - key: CORS_ALLOWED_ORIGINS
        value: https://resume-analyzer-nine-khaki.vercel.app

  - type: pserv
    name: resume-analyzer-db
    env: postgresql
    plan: free
    databaseName: resume_analyzer
    user: resume_user
